# Generated by Django 2.2 on 2021-11-30 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20211129_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id_news',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_news', to='app_news.News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('y', 'Активно'), ('n', 'Неактивно')], default='n', max_length=1, verbose_name='Статус новости'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
