# Generated by Django 2.2 on 2022-03-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='record_title',
            field=models.TextField(verbose_name='Заголовок записи'),
        ),
        migrations.AlterField(
            model_name='uploadingfiles',
            name='file',
            field=models.ImageField(blank=True, upload_to='blog_img/%Y/%m/%d', verbose_name='Загрузка изображения'),
        ),
    ]
