# Generated by Django 2.2 on 2021-11-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='name_author',
        ),
    ]
