# Generated by Django 2.2 on 2021-12-05 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок новости')),
                ('text_news', models.TextField(verbose_name='Текст новости')),
                ('update_news', models.DateTimeField(auto_now=True)),
                ('created_news', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('y', 'Активно'), ('n', 'Неактивно')], default='n', max_length=1, verbose_name='Статус новости')),
            ],
            options={
                'ordering': ['-created_news'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Имя комментатора')),
                ('text_comment', models.TextField(verbose_name='Текст комментария')),
                ('created_comment', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('id_news', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_news', to='app_users.News')),
            ],
            options={
                'ordering': ['-created_comment'],
            },
        ),
    ]
