# Generated by Django 2.2 on 2022-02-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_status', models.CharField(max_length=50, verbose_name='Статус новости')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedline_news', models.CharField(max_length=100, verbose_name='Заголовок новости')),
                ('text_news', models.TextField(verbose_name='Текст новости')),
                ('update_news', models.DateTimeField(auto_now=True)),
                ('created_news', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.News_status', verbose_name='Статус новости')),
            ],
            options={
                'ordering': ['-created_news'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(max_length=150, verbose_name='Текст комментария')),
                ('name_commentator', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя комментатора')),
                ('date_comment', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('news_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_comment', to='app_users.News')),
            ],
            options={
                'ordering': ['-date_comment'],
            },
        ),
    ]
