# Generated by Django 2.2 on 2022-02-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_news_status_print_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_status',
            name='print_flag',
        ),
        migrations.AddField(
            model_name='news',
            name='print_flag',
            field=models.BooleanField(default=False, verbose_name='Одобрить в печать'),
        ),
    ]
