# Generated by Django 2.2 on 2022-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_auto_20220215_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag_news',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тег новости'),
        ),
    ]
