# Generated by Django 2.2 on 2022-03-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20220322_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_user_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Аватар профиля'),
        ),
    ]
