# Generated by Django 2.2 on 2021-11-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя комментария')),
                ('body', models.TextField(verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-update_news']},
        ),
        migrations.AlterField(
            model_name='news',
            name='author_news',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_news.Author_news', verbose_name='Автор новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_news.Status_news', verbose_name='Статус новости'),
        ),
        migrations.AlterField(
            model_name='status_news',
            name='status_news',
            field=models.CharField(max_length=500, null=True, verbose_name='Статус новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Комментарий', to='app_news.Comment'),
        ),
    ]
