# Generated by Django 2.2 on 2022-02-10 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('verification_flag', models.BooleanField(default=False, verbose_name='Флаг верификации')),
                ('superuser_flag', models.BooleanField(default=False, verbose_name='Флаг супер юзера')),
                ('city', models.CharField(max_length=30, verbose_name='Город проживания')),
                ('count_news', models.IntegerField(default=0, verbose_name='Количество опубликованных новостей')),
                ('users', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
