# Generated by Django 2.2 on 2022-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_user', '0002_auto_20220207_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='superuser_flag',
            field=models.BooleanField(default=False, verbose_name='Флаг супер юзера'),
        ),
    ]
